[project]
authors = ["Jacob Valdez <jacob@deepshard.org>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Truffle SDK for Mojo"
name = "truffle"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
